version: '3'
services:
  web:
    environment:
      - VIRTUAL_HOST=${SP_HOST:-localhost}
      - DEBUG=true
    volumes:
      - ./apps/:${CATALINA_HOME}/webapps/apps/:ro

  nginx:
    ports:
      - "80:80"
