version: '3'
services:
  web:
    build:
      context: .
      args:
        - HARDCODE_HTTPS=${HARDCODE_HTTPS:-false}
    environment:
      - VIRTUAL_PORT=8080

  nginx:
    image: "jwilder/nginx-proxy"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

